application: jasonpythonproject
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /data
  script: datahandler.py
  
- url: /power
  script: datahandler.py

- url: /.*
  script: mainpage.py
  
 
